# Generated by Django 6.1 on 2026-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_actor_actor_bio_en_actor_actor_bio_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slogan_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
    ]
