# Generated by Django 6.1 on 2026-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_slogan_en_movie_slogan_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
