# Generated by Django 6.1 on 2026-08-25 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_genre_genre_name_alter_genre_genre_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_category', to='movie_app.category'),
        ),
    ]
