# Generated by Django 6.1 on 2026-08-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_genre_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genre_move', to='movie_app.genre'),
        ),
    ]
